import { ThemeProvider } from 'styled-components'
import './globals.css'
import { Inter } from 'next/font/google'
import { darkTheme } from './utils/Themes'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const Body = styled.div`
width : 100%; 
height : 100%;
`
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <StyledJsxRegistry>
        <ThemeProvider theme ={darkTheme}> 
        <Body> 
        {children}
        </Body>
        </ThemeProvider>
        </StyledJsxRegistry>
        </body>
    </html>
  )
}
